# Generated by Django 5.0.2 on 2024-05-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('health', models.CharField(max_length=100)),
                ('disease', models.CharField(max_length=100)),
                ('video_file', models.FileField(null=True, upload_to='videos/')),
            ],
        ),
    ]
